// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Notebook struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Topic        string    `json:"topic"`
	Content      string    `json:"content"`
	Deleted      bool      `json:"deleted"`
	LastModified time.Time `json:"last_modified"`
	CreatedAt    time.Time `json:"created_at"`
}
