// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotebook(ctx context.Context, arg CreateNotebookParams) (Notebook, error)
	DeleteNotebook(ctx context.Context, arg DeleteNotebookParams) (Notebook, error)
	GetNotebook(ctx context.Context, id uuid.UUID) (Notebook, error)
	ListNotebooks(ctx context.Context, arg ListNotebooksParams) ([]Notebook, error)
	SearchNotebooks(ctx context.Context, title string) ([]Notebook, error)
	UpdateNotebook(ctx context.Context, arg UpdateNotebookParams) (Notebook, error)
}

var _ Querier = (*Queries)(nil)
